# Generated by Django 4.2.27 on 2026-06-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stone_type', models.CharField(blank=True, max_length=100)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('bead_size', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('shape', models.CharField(blank=True, max_length=50)),
                ('size_info', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(max_length=500)),
                ('category', models.CharField(default='Gemstone Bracelets', max_length=100)),
                ('whatsapp_link', models.URLField(blank=True, max_length=800)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WristSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('cm', models.CharField(max_length=20)),
                ('inches', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
