# Generated by Django 6.0.6 on 2026-08-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_100pc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per pc for 100 pcs', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_10pc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per pc for 10 pcs', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_50pc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per pc for 50 pcs', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='1 pc price (default display price)', max_digits=10),
        ),
    ]
