# Generated by Django 5.2.15 on 2026-08-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_contactmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_unit',
            field=models.CharField(blank=True, default='per piece', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='1 pc price (default display price)', max_digits=10, null=True),
        ),
    ]
